### ISSUE TITLE
[Feature Request] Scale Lock

### ISSUE THREAD

**Issue by utdrmac** [stockto2/desktophero_django#18]
My son was designing his model yesterday. He added a robe/cloak. His model's chest was sticking out beyond the cloak. I told him he'd have to go to the bones and scale them down to get the chest smaller and "hide" it. Thinking about it now, probably could have just deleted the torso.

This was quite a pain to have to scale 2 groups, separately, on all 3 axis.

Would be nice, for situations like this where you want to proportionally scale something on all 3 axis.

Maybe 'S' + 'A' for All 3 Axis?

**Comment by stockto2** [comment]
Hi utdrmac, 

If you press s and then don't press an axis key, it will default to scaling all 3 axes.

Another way to fix it is to select the torso mesh and set it to None.
