### ISSUE TITLE
alignment or upload issue

### ISSUE THREAD

**Issue by cfalt** [stockto2/desktophero_django#23]
Hi, I could not find my file after uploading.  

I downloaded a model from DesktopHero, opened it in blender, and then placed the item in the hand of the character to get the scale and position correct.  It looked fine and I wanted to share the "Shoots First Blaster."

[solo_blaster.zip](https://github.com/stockto2/desktophero_django/files/1533604/solo_blaster.zip)

**Comment by stockto2** [comment]
Hi cfalt, try again now. I moved DesktopHero onto a new server and forgot to start the submission processing script.

**Comment by cfalt** [comment]
Still no luck on my end.  Maybe there is something wrong with my file? Can try to reference in MeshMixer and see if it shows up in the correct place from Blender.
Adjust scale or position does not make it appear.
When I click 'contribute' I go here http://new.desktophero3d.com/resources/contribute
and then select 'new uploader' http://new.desktophero3d.com/resources/contribute/upload_asset
Thank you for all of the hard work. It has me back in modeling software, building little things.

**Comment by cfalt** [comment]
OK, blender put it in a wrong place.  Got it to work by referencing it in Meshmixer? It also has bad geometry, so now to fix that

**Comment by stockto2** [comment]
Glad it's working, thanks for contributing!
