### ISSUE TITLE
Not able to contribute weapons/items.

### ISSUE THREAD

**Issue by ElsinoreBrewmaster** [stockto2/desktophero_django#25]
I tried to contribute a new weapon/item and it doesn't appear in the editor. I connected it to the right hand weapon slot and tried both the weapons and items categories. The upload finished and I logged out, cleared my browsing cache, then logged back in. The new weapon/item still does not appear in editor.

**Comment by ElsinoreBrewmaster** [comment]
Here's a log file. Hopefully, I checked the right options. 
[new.desktophero3d.com-1513291265187.log](https://github.com/stockto2/desktophero_django/files/1561013/new.desktophero3d.com-1513291265187.log)

**Comment by ElsinoreBrewmaster** [comment]
I think this might be the relevant section : 

hey
17:38:49.746 upload_asset:2518 
17:38:55.066 upload_asset:2518 
17:39:03.179 upload_asset:2518 
17:39:03.419 upload_asset:2518 
17:39:03.931 upload_asset:2518 
17:39:04.403 upload_asset:1071 Entering pose mode.
17:39:04.403 upload_asset:2518 
17:39:04.591 [Violation] 'requestAnimationFrame' handler took 182ms
17:39:04.636 upload_asset:2518 
17:39:05.059 upload_asset:2518 
17:39:05.387 upload_asset:2518 
17:39:15.698 upload_asset:1 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
17:39:56.129 Navigated to http://new.desktophero3d.com/editor/

**Comment by ElsinoreBrewmaster** [comment]
Here's the asset I tried to upload, in case it's relevant. 
[revolver.zip](https://github.com/stockto2/desktophero_django/files/1565086/revolver.zip)
![finishedrevolver](https://user-images.githubusercontent.com/34317751/34074205-036780e4-e278-11e7-842b-d6bad715a52a.jpg)

**Comment by stockto2** [comment]
Interesting. I'm wondering if the problem is due to the size of the model rather than the fact that it's a weapon. I have a suspicion that the server instance is too puny to handle the model processing.

Could you try these two tests for me?

1) Attach the gun model to a head or arm bone and see if it works

2) Try uploading a smaller file (1MB or less) as a weapon and see if that works

**Comment by ElsinoreBrewmaster** [comment]
Okay. I tried uploading Revolver.obj as a head. It processed it for a long time, then never appeared in the editor. Then I created a small weapon file, pointystick.obj (45.2KB), and uploaded it as a weapon. it worked. It seems the problem is with my model. Looking at other models I've uploaded, mrbunny1.obj is 7.01MB, mrbunny2.obj is 7.04MB, and combover.obj is 2.23MB. 

The problem resides in my model, obviously, but I'm not sure it's a simple file size issue. Maybe it's triangle count or some other type of complexity I introduced while creating it. I'll keep experimenting with it to see if I can find a way to make it work. I'll let you know what I find out, so you can add the info to the asset creation guide.

**Comment by ElsinoreBrewmaster** [comment]
Reducing the triangle count for each of the component parts seems to have done the trick. I got the file size down to 3.36MB. The upload worked correctly and the Revolver asset is now shared. 
![redrevolver](https://user-images.githubusercontent.com/34317751/34118497-fd564052-e3ec-11e7-9694-1c6cd7cc28bb.jpg)

**Comment by stockto2** [comment]
Thanks, I think I'll move DesktopHero onto a more powerful server and see if we still run into problems.

**Comment by stockto2** [comment]
(Great model, also)
