### ISSUE TITLE
items stuck and frozen when loading a character file

### ISSUE THREAD

**Issue by Xenon472** [stockto2/desktophero_django#47]
whenever I load a Character file some items becomes stuck forever, as example if the character had a cape  i cant remove it and if i try to add a differnt one instead of "swapping" the items as always it add the new one leaving the old one untouched

**Comment by stockto2** [comment]
Hmm, that's not good. My guess is that this is caused by clicking new items
before all the assets have finished loading.

**Comment by stockto2** [comment]
Let me know if this is still a problem for you.
