### ISSUE TITLE
Error upon loading STL file

### ISSUE THREAD

**Issue by TordTorden** [stockto2/desktophero_django#48]
So I recently stumbled upon your tool, and I found it to be absolutely excellent, and a good alternative when I only wanted to let my players send me their files for printing. I have access to a Cel Robox, and upon loading the STL file into the pre-print software for the robox, I got the following message:

![skjermbilde](https://user-images.githubusercontent.com/36534035/38572261-eeffdfea-3cf2-11e8-8062-3eae5b8ec2a5.PNG)

By loading the file, it ended up looking like this (numbers are in mm), and it' way smaller than it should be, and it's numbers doesn't fit with what's present in the infobox, and there is no Z-axis represented there.

![skjermbilde2](https://user-images.githubusercontent.com/36534035/38572263-ef2beafe-3cf2-11e8-8031-61455bc87281.PNG)

A closer look

![skjermbilde3](https://user-images.githubusercontent.com/36534035/38572264-ef5183c2-3cf2-11e8-871b-d61231edf0b5.PNG)

I haven't had a problem with self build models from Fusion 360, or downloaded ones from thingiverse yet, so I assume there is a problem with the exported model. I tried another one, and had the same issue. Scaling it works fine however, and as long as it wants to be sliced, it should work with the printer, I just thought I'd give you a heads up about it.

There is also another minor issue, where if you hit download the STL before the figure has finished rendering, you might end up with a model where only half of the components are present, and where the base is in the middle of it.

**Comment by stockto2** [comment]
Thanks for this report. I have seen this come up, it's usually means that
one of the assets that was used has an issue. I've found that most sliders
will be able to slice it anyway. If not, using netfabb or the windows mesh
repair tool works well. And you will need to resize it before you print.
I'll try to fix that in the next version.

**Comment by stockto2** [comment]
FYI, here's a link to the Microsoft's 3D model repair tool: https://tools3d.azurewebsites.net/
