### ISSUE TITLE
STL file not loading in Flashprint

### ISSUE THREAD

**Issue by Alasir** [stockto2/desktophero_django#51]
None of the generated STL files work for me. It refuses to load at all.

Im using the  Flashprint software that was delivered with my printer. Other STL files work fine.

**Comment by azurewraith** [comment]
I'm not familiar with Flashprint, but I'm guessing it's having an issue with non-manifold meshes.  I had a similar problem when I attempted to import into B9Creator.  What I had to do was use Meshmixer to convert to a solid mesh (turn the fidelity way up) then export to STL and then I had an easier time importing.  Hope this helps.

**Comment by stockto2** [comment]
I've noticed the same thing recently, and I'll have to dig deeper into why it's happening. In the meantime, if you import the model into Blender or some other 3D modeling program and re-export it it should be fine. You can also use Microsoft's 3D model repair tool: https://tools3d.azurewebsites.net/
