### ISSUE TITLE
Someone has uploaded my work as their own

### ISSUE THREAD

**Issue by DrkPally** [stockto2/desktophero_django#53]
Hello!  As I was scrolling through the "Headgear" section of desktop hero I noticed the "Helm Of The Champion." As you can see from https://www.thingiverse.com/thing:1875968/ on the second picture my Empire Soldier is wearing that helmet.  I am happy that my helmet has made it to your website, but I would appreciate it if the proper credit was given to the rightful creator.  Thanks!

**Comment by stockto2** [comment]
This asset has been removed.
