### ISSUE TITLE
Clothes clipping body

### ISSUE THREAD

**Issue by Helbrecht43** [stockto2/desktophero_django#54]
Almost all of the clothes do a lot of weird clipping when added to the male body. Here is one picture of one of the worst culprits.
![clipping](https://user-images.githubusercontent.com/39246119/39971075-30c01a6e-56aa-11e8-874d-9fbd0b936d33.jpg)

**Comment by stockto2** [comment]
I think that's just a broken clothing mesh that needs to be deleted. But you're right, sometimes the torso/legs stick out past the clothing. That will be something I'll look at with future models going forward. In the meantime you can try just deleting the torso mesh completely by setting it to None.
