### ISSUE TITLE
Can't load your STL files in FlashForge

### ISSUE THREAD

**Issue by tbeadlejr** [stockto2/desktophero_django#56]
I have a FlashForge Finder 3D printer which uses FlashPrint as it's slicing software. I tried downloading your starting character and tried to open it in FlashPrint and receive the error that it can't load.

Any suggestion?

**Comment by stockto2** [comment]
Hi there, I also have a FlashForge Finder and quite like it! I've noticed the same thing recently, and I'll have to dig deeper into why it's happening. In the meantime, if you import the model into Blender or some other 3D modeling program and re-export it it should be fine. You can also use Microsoft's 3D model repair tool: https://tools3d.azurewebsites.net/
